controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    num_aleatorio1:
        path: /intro-asignaturas
        controller: App\controller\AsignaturasController::index
        
