controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    num_aleatorio1:
        path: /mi-aleatorio
        controller: App\controller\AleatorioContorller::index
        
